# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/speci/vivado/sample_design/sample_design.cache/wt [current_project]
set_property parent.project_path C:/Users/speci/vivado/sample_design/sample_design.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths c:/Xilinx/vivado-library [current_project]
set_property ip_output_repo c:/Users/speci/vivado/sample_design/sample_design.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/speci/vivado/sample_design/sample_design.srcs/sources_1/new/design_2.v
add_files C:/Users/speci/vivado/sample_design/sample_design.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all C:/Users/speci/vivado/sample_design/sample_design.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/speci/vivado/sample_design/sample_design.srcs/sources_1/bd/design_1/design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/speci/vivado/sample_design/sample_design.srcs/constrs_1/imports/Xilinx/zybo-master.xdc
set_property used_in_implementation false [get_files C:/Users/speci/vivado/sample_design/sample_design.srcs/constrs_1/imports/Xilinx/zybo-master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_2 -part xc7z010clg400-1


write_checkpoint -force -noxdef design_2.dcp

catch { report_utilization -file design_2_utilization_synth.rpt -pb design_2_utilization_synth.pb }
