# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/speci/vivado/custom_ip/custom_ip.srcs/sources_1/bd/design_1/ip/design_1_myip_0_3/design_1_myip_0_3.xci
# IP: The module: 'design_1_myip_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/speci/vivado/custom_ip/custom_ip.srcs/sources_1/bd/design_1/ip/design_1_myip_0_3/src/zybo-master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_myip_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/speci/vivado/custom_ip/custom_ip.srcs/sources_1/bd/design_1/ip/design_1_myip_0_3/design_1_myip_0_3.xci
# IP: The module: 'design_1_myip_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/speci/vivado/custom_ip/custom_ip.srcs/sources_1/bd/design_1/ip/design_1_myip_0_3/src/zybo-master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_myip_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
