# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/speci/vivado/hdmi_vga_pxl_ip/hdmi_vga_pxl_ip.cache/wt [current_project]
set_property parent.project_path C:/Users/speci/vivado/hdmi_vga_pxl_ip/hdmi_vga_pxl_ip.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/speci/vivado/hdmi_vga_pxl_ip/hdmi_vga_pxl_ip.srcs
  c:/Xilinx/vivado-library
} [current_project]
set_property ip_output_repo c:/Users/speci/vivado/hdmi_vga_pxl_ip/hdmi_vga_pxl_ip.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/speci/vivado/hdmi_vga_pxl_ip/hdmi_vga_pxl_ip.srcs/sources_1/new/pixel_processor.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/speci/vivado/hdmi_vga_pxl_ip/hdmi_vga_pxl_ip.srcs/constrs_1/imports/Xilinx/zybo-master.xdc
set_property used_in_implementation false [get_files C:/Users/speci/vivado/hdmi_vga_pxl_ip/hdmi_vga_pxl_ip.srcs/constrs_1/imports/Xilinx/zybo-master.xdc]


synth_design -top pixel_processor -part xc7z010clg400-1


write_checkpoint -force -noxdef pixel_processor.dcp

catch { report_utilization -file pixel_processor_utilization_synth.rpt -pb pixel_processor_utilization_synth.pb }
